### ISSUE TITLE
Terrain, triplanar and forward rendering

### ISSUE THREAD

**Issue by andybak** [Josh015/Alloy#1]
The docs warn against this for performance reasons: https://alloy.rustltd.com/documentation/shader/terrain

However - for VR anything other than forward isn't really an option. Is there any way around this conundrum?

**Comment by Josh015** [comment]
Not really, no. For our own VR project we've also been forced to use the forward renderer because we need MSAA. So when it comes to our splat-based shader materials we have been managing the cost by aggressively disabling the normal and packed maps . 

Please note, this channel should be used for Alloy development questions. Usage questions should be directed to our Unity forums thread:
https://forum.unity.com/threads/alloy-physical-shader-framework-version-3-for-unity-5.305178/
